In [2]:
from google.colab import files
uploaded = files.upload()

Saving BankNote_Authentication.csv to BankNote_Authentication (1).csv

In [3]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.linear_model import LogisticRegression

In [4]:
data = pd.read_csv("BankNote_Authentication.csv")
data
print(data.head())
print(data.columns)

   variance  skewness  curtosis  entropy  class
0   3.62160    8.6661   -2.8073 -0.44699      0
1   4.54590    8.1674   -2.4586 -1.46210      0
2   3.86600   -2.6383    1.9242  0.10645      0
3   3.45660    9.5228   -4.0112 -3.59440      0
4   0.32924   -4.4552    4.5718 -0.98880      0
Index(['variance', 'skewness', 'curtosis', 'entropy', 'class'], dtype='object')

In [6]:
X = data.drop("class", axis=1)
y = data["class"]

In [7]:
print(X.shape)
print(y.shape)

(1372, 4)
(1372,)

In [8]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

In [9]:
model = LogisticRegression(max_iter=1000)

In [11]:
model.fit(X_train, y_train)

LogisticRegression(max_iter=1000)

In [12]:
y_pred = model.predict(X_test)

In [14]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.9854545454545455

In [18]:
data[data['class']==0].head()

   variance  skewness  curtosis  entropy  class
0   3.62160    8.6661   -2.8073 -0.44699      0
1   4.54590    8.1674   -2.4586 -1.46210      0
2   3.86600   -2.6383    1.9242  0.10645      0
3   3.45660    9.5228   -4.0112 -3.59440      0
4   0.32924   -4.4552    4.5718 -0.98880      0

In [19]:
data[data['class']==1].head()

     variance  skewness   curtosis  entropy  class
762  -1.39710   3.31910  -1.392700 -1.99480      1
763   0.39012  -0.14279  -0.031994  0.35084      1
764  -1.66770  -7.15350   7.892900  0.96765      1
765  -3.84830 -12.80470  15.682400 -1.28100      1
766  -3.56810  -8.21300  10.083000  0.96765      1

In [21]:
variance = float(input("Enter Variance: "))
skewness = float(input("Enter Skewness: "))
curtosis = float(input("Enter Curtosis: "))
entropy = float(input("Enter Entropy: "))

user_data = [[variance, skewness, curtosis, entropy]]

prediction = model.predict(user_data)

if prediction[0] == 0:
    print("Original Bank Note")
else:
    print("Fake Bank Note")

Enter Variance: 4.54590
Enter Skewness: 8.1674
Enter Curtosis: -2.4586
Enter Entropy: -0.46210
Original Bank Note

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(